version: '2'
services:
    dcultimatebot-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/dcultimatebot/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=dcultimatebot
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
